server:
  port: 8088
---
spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            preLogger: true
            postLogger: true
      routes:
        - id: training-svc
          uri: http://sketchbrain-trainer-svc:9000
          predicates:
            - Path=/api/trainer/**
          filters:
            - name: BackendFilter
              args:
                baseMessage: Spring Cloud Gateway BackendFilter
                preLogger: true
                postLogger: true
          metadata:
            connect-timeout: 2500
            response-timeout: 2500
        - id: backend-svc
          uri: http://sketchbrain-backend-svc:8080
          predicates:
            - Path=/api/server/**
          filters:
            - name: BackendFilter
              args:
                baseMessage: Spring Cloud Gateway BackendFilter
                preLogger: true
                postLogger: true
          metadata:
            connect-timeout: 2500
            response-timeout: 2500
        - id: fileserver-svc
          uri: http://sketch-brain-file-server-svc:8080
          predicates:
            - Path=/api/file/**
          filters:
            - name: FileServerFilter
              args:
                baseMessage: Spring Cloud Gateway FileServerFilter
                preLogger: true
                postLogger: true
          metadata:
            connect-timeout: 2500
            response-timeout: 2500
        - id: ui-svc
          uri: http://sketchbrain-ui-svc:3000
          predicates:
            - Path=/**
          filters:
            - name: UIFilter
              args:
                 baseMessage: Spring Cloud Gateway UIFilter
                 preLogger: true
                 postLogger: true
          metadata:
            connect-timeout: 2500
            response-timeout: 2500

