apiVersion: v1
kind: Service
metadata:
   name: sketchbrain-gateway-svc
   labels:
      app: sketchbrain-gateway
spec:
   type: ClusterIP
   ports:
   - name: gateway-port
     port: 8088
     targetPort: 8088
   selector:
        app: sketchbrain-gateway

